### ISSUE TITLE
support writing to String instead of File?

### ISSUE THREAD

**Issue by evbo** [jwodder/serde-jsonlines#1]
Hi,

I do not have disk where this code runs and would ideally write out the raw JSON Lines data as a byte array to my code that separately handles uploading the bytes to a file in a server. 

Would that be possible to support writing to a String in memory?

**Comment by jwodder** [comment]
You mention writing to both Strings and byte arrays.  If writing to only the latter is acceptable, you can do this right now, as `Vec<u8>` implements `std::io::Write`, so you can call `WriteExt::write_json_lines()` on a `Vec<u8>` or wrap it in a `JsonLinesWriter`.  If you still need a String after that, you can use [`String::from_utf8()`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8).  Is that acceptable?

**Comment by evbo** [comment]
I also realized I can just iterate over each struct and using `serde_json` to serialize it, concatenate with newlines, and then convert the whole thing to one big byte array.

Sounds like either approach will work, but using this library will be more ergonomic by the sounds of it? Maybe more performance by avoiding String processing?

**Comment by evbo** [comment]
@jwodder am I close to getting this working?

```rust
error[E0277]: the trait bound `Vec<u8>: AsRef<Path>` is not satisfied
    |
103 |       write_json_lines(results, &arr)?;
    |       ---------------- ^^^^^^^ the trait `AsRef<Path>` is not implemented for `Vec<u8>`
    |       |
    |       required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsRef<T>`:
              <Vec<T, A> as AsRef<Vec<T, A>>>
              <Vec<T, A> as AsRef<[T]>>
```

**Comment by jwodder** [comment]
@evbo You didn't provide any code for reproducing the error, but it appears that you are calling [the `write_json_lines()` function](https://docs.rs/serde-jsonlines/latest/serde_jsonlines/fn.write_json_lines.html) with a `Vec<u8>` as the first argument.  That is incorrect, as that function is used for writing to a file specified by a filepath, yet you want to write to a `std::io::Write` instance.  The `write_json_lines()` that I referred to in my previous comment is [the `write_json_lines()` method provided by the `WriteExt` trait](https://docs.rs/serde-jsonlines/latest/serde_jsonlines/trait.WriteExt.html#method.write_json_lines), which can be used by placing `use serde_jsonlines::WriteExt;` at the top of your source file and then doing `results.write_json_lines(&arr);`.

**Comment by evbo** [comment]
@jwodder thank you, unfortunately I didn't see this soon enough and discovered I could use `serde_json` directly, though I'm not sure how many best practices I'm violating - it is however very simple:

```rust
let mut results: Vec<u8> = Vec::new();
for value in arr {
  serde_json::to_writer(&mut results, &value)?;
  serde_json::to_writer(&mut results, b"\n")?;
}
```
